#!/usr/bin/env python
"""mythril.py: Bug hunting on the Ethereum blockchain
   http://www.github.com/b-mueller/mythril
   """
import mythril.interfaces.cli

if __name__ == "__main__":
    mythril.interfaces.cli.main()
